version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres: